### ISSUE TITLE
Cell values beyond the 27th column are not read

### ISSUE THREAD

**Issue by jkyeung** [PydPiper/pylightxl#13]
It looks like column AA is the rightmost column read by pylightxl. Columns AB and beyond all come up as empty.

For example, the last three cells in this sheet show up as empty in pylightxl:

[sample2.xlsx](https://github.com/PydPiper/pylightxl/files/4608093/sample2.xlsx)

But AB1 should be 27, AC1 should be 28, and AD1 should be 29.

**Comment by PydPiper** [comment]
hi jkyeung,

thank you for submitting this issue. It does appear to be a bug, and we are looking into the fix now.

**Comment by PydPiper** [comment]
bug fixed in version 1.43 and the current git repo. Thank you for catching this and reporting it.

![image](https://user-images.githubusercontent.com/35475223/83205420-5918e900-a103-11ea-842a-7112f8f572c2.png)
