### ISSUE TITLE
I like the lightweight Library, so have two expectations 

### ISSUE THREAD

**Issue by joylin1984** [PydPiper/pylightxl#16]
I like the lightweight Library， Thank you for your jobs.

1. write cell with formatting
2. improve performance while maintaining lightweight

**Comment by PydPiper** [comment]
Hi Joylin! We appreciate your feedback and thank you for considering using pylightxl for your projects! We are currently working on expanding the database functionality and improving read/write performance. We don't anticipate a new version release till late aug. Please check back then for updates
