### ISSUE TITLE
Read content from stream

### ISSUE THREAD

**Issue by moonso** [PydPiper/pylightxl#25]
**Pylightxl Version**:
1.47
**Python Version**:
3.7

**Summary of Feature**:
Hi, thanks for a nice package. Is there any way to read from a file stream?
Like:

```python
with open("my_file.xlsx", "r") as infile:
    db = pylightxl.readxl(infile)
```

**Suggestion for fix**

Add a new argument to readxl like `pylightxl.readxl(file_content=excel_file.read())`

**Comment by PydPiper** [comment]
Hi thank you for considering using pylightxl. Not at the moment. We are currently working on parsing from stream when file size limit is detected for fast and efficient reading

**Comment by Warqus** [comment]
@PydPiper Thanks for the amazing library. What is the status on this?

**Comment by PydPiper** [comment]
Hi Warqus, i opened this issue up seeking for some help, but havent received any takers. I will try to take a stab at it today and will let you know how far i get :)

**Comment by Warqus** [comment]
@PydPiper Thanks for your reaction! The reason why I asked is because I want to use this library in Django, since it has no dependencies. Pandas is way too big.

The issue I stumbled upon was that I want to read a file from a upload with the file field. I tried using the file name and path name, but both were not found. However, I am able to read a filefield with 'with open():'.

**Comment by PydPiper** [comment]
@Warqus That is interesting that pointing the reader to the file path did not work. Are you sure that file exists and is downloaded with django? 

However i will add the `with block` later today then and we can give it a test on your side to see if it resolved the issue

**Comment by PydPiper** [comment]
@Warqus @moonso please check out the current master branch for the update. Use `pip install git+https://github.com/PydPiper/pylightxl.git` to install v1.55b and let me know if you have any questions/issues on your end using it. Note that you will have to feed the open object a `rb`

for example:
```
import pylightxl

with open('excel.xlsx', 'rb') as f:
    db = pylightxl.readxl(f)
```

**Comment by Warqus** [comment]
@PydPiper I can't thank you enough! Really awesome work. I tested it within Django and it works :)

I had to use a small workaround. In Django, using a freshly uploaded file is apparently different than using an already uploaded file. My workaround:

```
  try:
      # freshly uploaded files
      db = pylightxl.readxl(file, ws=worksheets)
      
  except zipfile.BadZipFile:
      
      # already uploaded files
      db = pylightxl.readxl(file.path, ws=worksheets)
```

**Comment by PydPiper** [comment]
@Warqus awesome news! I will look into your work around after work today and we’ll try again. Once this is set I’ll release a new version on pypi

**Comment by PydPiper** [comment]
@Warqus i uploaded a new version that hopefully removes the work-around you needed to add. Can you let me know if that works and ill wrap this up if it is all okay

**Comment by Warqus** [comment]
@PydPiper Thanks for trying. Unfortunately it didn't work. 

I am not sure how many people will have this problem in the future, so I don't mind using the BadZipFile exception as fix.

**Comment by PydPiper** [comment]
pypi version 1.55 released that fixes this issue. Thank you for considering using pylightxl!
