### ISSUE TITLE
writexl does not handle creating files in correct directory

### ISSUE THREAD

**Issue by bhanu-subramanya** [PydPiper/pylightxl#32]
Version: 1.51 
Python Version: 3.8.2
**Summary of Bug/Feature**:
There are two issues in writexl_alt_writer function called by writexl 
1) It does not handle use case where a path with dirname/filename is passed. It ends up writing files in "." instead of creating/writing files in "dirname". 
2) Line 569 uses a windows directory separator ("\") instead of using os independent approach to create path

**Traceback**:
None. I have suggested some fixes and diff between fixed version vs. 1.51

**Suggestion for fix**:
In terms of writing file to correct directory, as part of moving zipped up file out of temp folder, 
- first get an absolute path name for the newly created file (filename)
- pop back to the directory where you were running (os.chdir(old_dir))
- create targetpath name based on the path that was passed in (could be relative name and needs to handle current dir)
- call shutil.move with filename and targetpath
- Here is the diff between 1.51 (<). and working version (>)
- 565a566,570
>     # to complete move, get absolute path, change back to directory where you were running and 
>     # use the pathname received to move it to right place
>     filepath = os.getcwd() + "/" + filename
>     os.chdir(old_dir)
>     targetpath = os.path.split(path)[0] if os.path.split(path)[0] != "" else "." 
567c572
<         shutil.move(filename, old_dir)
---
>         shutil.move(filepath, targetpath)
569,571c574,575
<         os.remove(old_dir + '\\' + filename)
<         shutil.move(filename, old_dir)
<     os.chdir(old_dir)
---
>         os.remove(os.path.join(old_dir, filename))
>         shutil.move(filename, targetpath)

**Comment by PydPiper** [comment]
Hi bhanu-subramanya, thank you for submitting this issue. I am working through the fix at the moment and will release a new version later today!

**Comment by PydPiper** [comment]
@v1.53 fixed the bug
