### ISSUE TITLE
Typo In Error Message

### ISSUE THREAD

**Issue by jackcsk** [PydPiper/pylightxl#33]
**Pylightxl Version**: 1.53
**Python Version**: 3.9.2

**Summary of Bug/Feature**:
On `readxl_check_excelfile(fn)`, the error message:
`UserWarning('pylightxl - File ({}) does not exit.'.format(fn))` has a typo:
`exit` -> `exist`

**Traceback**:

**Suggestion for fix**:
Correct the typo

**Comment by PydPiper** [comment]
Hi Jackcsk. Thanks for considering pylightxl and submitting this! It is fixed on the current github master, this will be rolled into the next release
