### ISSUE TITLE
Issue reading Excel file

### ISSUE THREAD

**Issue by UdbhavPrasad072300** [PydPiper/pylightxl#39]
**Pylightxl Version**:  1.54
**Python Version**: 3.8.6

**Summary of Bug/Feature**: Issue reading an excel file

**Traceback**:
```
Traceback (most recent call last):
  File "C:/Users/udbha/Downloads/Excel Formatter/mywork/change.py", line 12, in <module>
    main()
  File "C:/Users/udbha/Downloads/Excel Formatter/mywork/change.py", line 7, in main
    db = xl.readxl(fn=PATH)
  File "C:\Users\udbha\AppData\Local\Programs\Python\Python38\lib\site-packages\pylightxl\pylightxl.py", line 118, in readxl
    wb_rels = readxl_get_workbook(fn)
  File "C:\Users\udbha\AppData\Local\Programs\Python\Python38\lib\site-packages\pylightxl\pylightxl.py", line 215, in readxl_get_workbook
    rId = tag_sheet.get('{' + ns['r'] + '}id')
KeyError: 'r'

Process finished with exit code 1
```

**Suggestion for fix**: I do not know.

MY CODE:
```
import pylightxl as xl


def main():
    PATH = "document.xlsx"
    NEW_PATH = "done_document.xlsx"
    db = xl.readxl(fn=PATH)
    xl.writexl(db=db, fn=NEW_PATH)


if __name__ == "__main__":
    main()
```

My excel file is excel 2010, which versions of excel is this library capable of handling?

**Comment by PydPiper** [comment]
Hi, thanks for considering using pylightxl. Pylightxl supports 2003+ excel files (.xlsx) files. Is it possible for you to attach a sample file that gave you this error?

**Comment by UdbhavPrasad072300** [comment]
I cannot add the excel file because it contains confidential information from my current workplace but I can say it is from an output file from openpyxl (which I believe is excel 2010).

**Comment by PydPiper** [comment]
Thank you for the additional information. We will try to recreate the issue on our end with openpyxl and get back to you.

**Comment by PydPiper** [comment]
Unable to replicate the issue with openpyxl created spreadsheet, however we did include a exception in the latest master branch. Can you pip install git+https://github.com/PydPiper/pylightxl.git and see if that fixed your issue?
