### ISSUE TITLE
Issues reading range of cells, each cells have decimals

### ISSUE THREAD

**Issue by JavierRenero** [PydPiper/pylightxl#40]
**Pylightxl Version**: 1.54
**Python Version**: 3.9.2

**Summary of Bug/Feature**: Issues reading range of cells, each cells have decimals

**Traceback**: i do not know how to do it

**Suggestion for fix**: No clue

**My Code**:

>  db = xl.readxl('IrisMod.xlsx')
    conjEntrenoList = db.ws('Hoja1').range('A1:E135')
    conjTestList = db.ws('Hoja2').range('A1:E15')

**Comment by PydPiper** [comment]
Hi Javier, thank you for considering using pylightxl. The current tests run a series of tests against various data types, integers, floats, strings, formulas and they are all showing appropriate results. Can you provide a bit more information on what the issue is that you are seeing? We were unable to replicate the issue from our end.

**Comment by JavierRenero** [comment]
i can give u the excel if  you want to replicate the error. Some funtion names and tag ar in spanish if u need traduction i will help you.
[IrisMod.xlsx](https://github.com/PydPiper/pylightxl/files/6403525/IrisMod.xlsx)
[tryFloat.txt](https://github.com/PydPiper/pylightxl/files/6403546/tryFloat.txt)

**Comment by JavierRenero** [comment]
tryfloat if the code thank you for your time.

**Comment by JavierRenero** [comment]
you finally solve it or not clue of the error

**Comment by PydPiper** [comment]
please do a ``pip install git+https://github.com/PydPiper/pylightxl.git -U`` off of github that has the fix. We will include the fix in the next pypi release shortly

**Comment by JavierRenero** [comment]
it still happens i don't know how to solve it

**Comment by PydPiper** [comment]
hi @JavierRenero can you try and uninstall pylightxl and install it via `pip install git+https://github.com/PydPiper/pylightxl.git` the new version will be released shortly on pypi

**Comment by JavierRenero** [comment]
I already did it.
![image](https://user-images.githubusercontent.com/47631050/117996583-8fff0380-b342-11eb-9a4b-e3e2631187de.png)

**Comment by JavierRenero** [comment]
and it still happend.

Output:
`[[0.22222222222222213, 0.6249999999999999, 0.06779661016949151, 0.04166666666666667, -1],...`
Should be:
![image](https://user-images.githubusercontent.com/47631050/117996876-d18fae80-b342-11eb-9d6b-ca3ebede2f1f.png)

**Comment by PydPiper** [comment]
i am not seeing the error there. The integer -1 is still an integer -1

**Comment by JavierRenero** [comment]
what happens is that in some position the number increases by a decimal

**Comment by PydPiper** [comment]
Here is the raw data out of your spreadsheet. There is no rounding or truncation done by pylightxl. It is directly ready from the full data that excel stores:
![image](https://user-images.githubusercontent.com/35475223/117998925-345c5800-b2f9-11eb-9306-58b91d7f5b17.png)

**Comment by JavierRenero** [comment]
okay it is correct my fault it is correctly done thanks you any ways, is just excel that truncation the numbers on the interface
