### ISSUE TITLE
py2.7 must be 2.7.18 ?

### ISSUE THREAD

**Issue by qq2898** [PydPiper/pylightxl#43]
Does pylightxl  SUPPORT other small version of python 2.7 like 2.7.10~ 2.7.17 ?

**Comment by PydPiper** [comment]
Hi @qq2898, thank you for considering using pylightxl. The original tests were run on python2.7.18, however I created a docker container for 2.7.10 and all tests passed! You are safe to use pylightxl on python2.7.10.
