### ISSUE TITLE
Wrong index assignment: self.size[1] should be self.size[0]

### ISSUE THREAD

**Issue by zhanilia** [PydPiper/pylightxl#47]
https://github.com/PydPiper/pylightxl/blob/d943773734eb72888d9fc5abdf3e8a553317cb0a/pylightxl/pylightxl.py#L1871-L1888

**Comment by PydPiper** [comment]
@zhanilia thank you for catching this! I pushed the fix to the master. We are waiting on a few more updates before we release a new version on pypi, but for now you can install via the master branch.
