### ISSUE TITLE
Multiline string not working in writecsv

### ISSUE THREAD

**Issue by Darcy-C** [PydPiper/pylightxl#49]
**Pylightxl Version**: 1.55
**Python Version**: 3

**Summary of Bug/Feature**:  
Method `writecsv `does not support multiline contents (cell that includes "\n"), which will break the database structure sometime

**Suggestion for fix**:

My easiest implementation
```python
def q(i):
    return '"' + i.replace('"', '""') + '"'
f.write(delimiter.join(map(q, row)))
f.write('\n')
```
https://github.com/PydPiper/pylightxl/blob/b17a50e3ab6c5544dd6fe9129bdbabb2123983c6/pylightxl/pylightxl.py#L1343-L1344

**Comment by PydPiper** [comment]
Hi @Darcy-C thank you for considering using pylightxl for your project. I am taking a look at this issue today

**Comment by PydPiper** [comment]
Hi @Darcy-C the issue had been resolved. New line `'\n'` will be removed within strings to prevent the writer writing the same row on multiple lines. Thank you for submitting this and let us know if you find anything else!
