### ISSUE TITLE
Formula: values ​​that depend on a formula are not updated

### ISSUE THREAD

**Issue by alexvr8282** [PydPiper/pylightxl#61]
**Pylightxl Version**: 1.58
**Python Version**: 3.9

**Summary of Bug/Feature**: I've a excel with 3 sheets where there are many formulas. When i changed values on a sheet on other sheets i don't see updating of the value that it dependes from a formula.

**Comment by PydPiper** [comment]
Hi @alexvr8282  thank you for considering using pylightxl. So currently pylightxl works on static values/formulas of what it extracts from excel on time of read. It does not update the formulas/values until you load it up in excel. There are other libraries out there like xlwings that would handle dynamic updating. Hope that helps
