### ISSUE TITLE
a question in readxl_get_workbook

### ISSUE THREAD

**Issue by newhying** [PydPiper/pylightxl#65]
def readxl_get_workbook(fn):
.......
    for tag_sheet in root.findall('./default:sheets/default:sheet', ns):
        name = tag_sheet.get('name')
        try:
            rId = tag_sheet.get('{' + ns['r'] + '}id')
        except KeyError:
            # the output of openpyxl can sometimes not write the schema for "r" relationship
            rId = tag_sheet.get('id')
        sheetId = int(re.sub('[^0-9]', '', rId))
        wbrels = readxl_get_workbookxmlrels(fn)
        rv['ws'][name] = {'ws': name, 'rId': rId, 'order': sheetId, 'fn_ws': wbrels[rId]}
.....

readxl_get_workbookxmlrels  is run many times

    wbrels = readxl_get_workbookxmlrels(fn)
    for tag_sheet in root.findall('./default:sheets/default:sheet', ns):
        name = tag_sheet.get('name')
        try:
            rId = tag_sheet.get('{' + ns['r'] + '}id')
        except KeyError:
            # the output of openpyxl can sometimes not write the schema for "r" relationship
            rId = tag_sheet.get('id')
        sheetId = int(re.sub('[^0-9]', '', rId))
        rv['ws'][name] = {'ws': name, 'rId': rId, 'order': sheetId, 'fn_ws': wbrels[rId]}

is run faster

**Comment by PydPiper** [comment]
@newhying thank you for submitting this. I agree moving the `readxl_get_workbookxmlrels` outside the tool will be faster. There is a potential that external tools may write each sheet differently. I can make this update however it may get reverted if others run into issues due to this
