### ISSUE TITLE
Reading CSVs from a file object

### ISSUE THREAD

**Issue by tbc399** [PydPiper/pylightxl#67]
**Pylightxl Version**:
1.59
**Python Version**:
3.10.0

**Summary of Bug/Feature**:
I'm scouting out libraries to use for parsing both csv and xlsx files, and I came across pylightxl. I like it since it can do both, and it's obviously lightweight. I'm wondering if there's a particular reason `readcsv()` is not able to read from a file object. If it's strategic, no worries. If it's just a matter of "not there yet", I'd be happy to submit a PR if you're okay with outside contributions.

Also, nice work!

**Comment by PydPiper** [comment]
Hi @tbc399 thank you for considering using pylightxl for your project! You hit it on the head, it's simply just not there yet since it has not been requested until now. I 100% welcome contributions if you want to take a crack at it!

**Comment by tbc399** [comment]
Great. I'll do some poking and prodding to figure out what needs to be done to get this in. Thanks!

**Comment by PydPiper** [comment]
Hey @tbc399 I've added stringIO support to readxl() function. It will be part of v1.61 release later today
