### ISSUE TITLE
(feature request) please consider adding type defintions

### ISSUE THREAD

**Issue by ZeeD** [PydPiper/pylightxl#69]
**Pylightxl Version**: 1.59
**Python Version**: 3.9

**Summary of Bug/Feature**: at the moment pylightxl doesn't use types, nor it expose them. So tools like `mypy` cannot check the user interactions

**Traceback**: 

**Suggestion for fix**:add typing annotations to the module

**Comment by PydPiper** [comment]
@ZeeD Thank you for considering using pylightxl for your project. This should be an easy add, we'll just have to make sure it is py2 backwards compatible looks like [here](https://mypy.readthedocs.io/en/stable/python2.html) is what we will need to follow

**Comment by tpc1095** [comment]
Thank you for doing this work. I am using Pylance (seems to be the default for Visual Studio Code) and it highlights a small number of possibly serious type issues. I am looking forward to using the new version.

**Comment by PydPiper** [comment]
added in v1.61
