### ISSUE TITLE
Type hinting issue

### ISSUE THREAD

**Issue by Daenara** [PydPiper/pylightxl#70]
**Pylightxl Version**: 1.5.9
**Python Version**: 3.8

**Summary of Bug/Feature**: In the quickstart guide for reading excel files it states:
```
# pylightxl also supports pathlib as well
my_pathlib = pathlib.Path('folder1/folder2/excelfile.xlsx')
db = xl.readxl(my_pathlib)
```
This works, but when adding that to my IDE (pycharm) it complains about a path object not being a string but a Path object. This is just a typehinting issue, but I thought I would report it anyway.

**Suggestion for fix**: Just replace the string type hinting with a union of string and path

**Comment by PydPiper** [comment]
Hey @Daenara thank you for submitting this. Sorry for the delay. The v1.61 will have typing that will be release later today!
