### ISSUE TITLE
Add feature to write to a named cell

### ISSUE THREAD

**Issue by bRitch022** [PydPiper/pylightxl#72]
**Pylightxl Version**: 1.59
**Python Version**: 3.8.10

**Summary of Bug/Feature**:
### Feature Request
Add ability to write to a named cell

**Traceback**:

**Suggestion for fix**:

**Comment by PydPiper** [comment]
Hey @bRitch022 i saw your MR, i am pull it down now to run some tests and fix up a few minor things on it before i merge it. Thanks for contributing!

**Comment by PydPiper** [comment]
Hey @bRitch022 i just released v1.60 that has the namedrange features you were looking for. Let me know if anything else comes up. It is a bit different in structure than your MR so i am going to close that out. I did use what you had as a benchmark but wanted to keep the organization the same through the entire pylightxl project. Thanks again for submitting these issues!
