### ISSUE TITLE
Repository tags out of sync with PyPi release

### ISSUE THREAD

**Issue by grawlinson** [PydPiper/pylightxl#74]
I package this for the [AUR](https://aur.archlinux.org/packages/python-pylightxl) using git tags, and this repository doesn't seem to have a tag associated with the recent release (1.60 on PyPi).

I'd appreciate if a tag for 1.60 was pushed to the repository. Thanks! :smile:

**Comment by PydPiper** [comment]
@grawlinson sorry about that, totally spaced adding the recent release as a tag. All set now. Thanks for the reminder! :)
