### ISSUE TITLE
pylightxl.Database.ws_names returns incorrect sheet names in some cases

### ISSUE THREAD

**Issue by flc** [PydPiper/pylightxl#75]
**Pylightxl Version**: 1.60
**Python Version**: 3.9.14

**Code to reproduce the problem**:
```
import pylightxl

path = 'test_sheet.xlsx'
db = pylightxl.readxl(fn=path)
print(db.ws_names)
```
The output is:
```
["'#3969'", '#3969']
```

However the file contains only 1 sheet named `#3969`.
The weird thing is that if I rename the sheet to `sheet` for example, save it in LibreOffice (see the attached `test_sheet_rename.xlsx`), then I get from the above code what is expected: `ws_names` return only 1 sheet named `sheet`.

[test_sheet.xlsx](https://github.com/PydPiper/pylightxl/files/9779845/test_sheet.xlsx)
[test_sheet_rename.xlsx](https://github.com/PydPiper/pylightxl/files/9779975/test_sheet_rename.xlsx)

**Comment by flc** [comment]
the problem seems to be the difference between these two:

```
<sheet name="#3969" sheetId="1" state="visible" r:id="rId2"/>
```

```
<definedName function="false" hidden="true" localSheetId="0" name="_xlnm._FilterDatabase" vbProcedure="false">&apos;#3969&apos;!$D$1:$D$963</definedName>
```

because
`#3969` != `&apos;#3969&apos;` aka `'#3969'`

xlrd==1.2.0:

**Comment by alexlawriewood** [comment]
I also noticed this as a regression when moving from 1.59 to 1.60, working with an Excel spreadsheet exported by an inventory tool.

**Comment by PydPiper** [comment]
@flc and @alexlawriewood Thank you for bringing this to our attention! Sorry about the delay, but i just had a chance to look into this and i am rolling out 1.61 that will fix this issue!

**Comment by flc** [comment]
Hi @PydPiper, thanks very much for the fix!
However, I briefly checked the fixed code and I wonder what happens if a sheet name actually contains a single quote. I think that would lead to an incorrect behavior again.

**Comment by LuiMal** [comment]
> Hi @PydPiper, thanks very much for the fix! However, I briefly checked the fixed code and I wonder what happens if a sheet name actually contains a single quote. I think that would lead to an incorrect behavior again.

Im having a pretty similar problem, but my code is a little to complex and ugly to share.. i think it fits what you're describing. Basically my code checks if some keywords are in the sheet, if it finds them it creates an entry in a dictionary with the all the content within that sheet, so it ignores empty sheets while importing the data. And if i look at the worksheet names list using "pylightxl.readxl('the path to the excel file').ws_names" there is a bunch of sheets that dont appear when i manually open the file. They should all be ignored while importing the data, but some of these "ghost pages" (the non empty ones) are being imported along and causing a lot of headache.
